import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import Footer from "./footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex justify-center items-center gap-6 bg-black text-white py-4 px-5 text-sm">
            <li className="hover:text-blue-500">
              <Link href="/">Home</Link>
            </li>
            <li className="hover:text-blue-500">
              <Link href="/about">About</Link>
            </li>
            <li className="hover:text-blue-500">
              <Link href="/blogs">Blogs</Link>
            </li>
            <li className="hover:text-blue-500">
              <Link href="/posts">Posts</Link>
            </li>
            <li className="hover:text-blue-500">
              <Link href="/dashboard">Dashboard</Link>
            </li>
          </ul>
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
